import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// @ts-ignore: Allow side-effect CSS import without type declarations
import "./globals.css";
// @ts-ignore: Allow side-effect CSS import without type declarations
import "bootstrap/dist/css/bootstrap.min.css";
import Footer from "./components/footer/Footer";
import Nav from "./components/nav/Nav";
import { JSX } from "react";
import BootstrapClient from "./components/BootstrapClient";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NexCart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} d-flex flex-column min-vh-100`}
      >
       
          <Nav />
 <div className="container flex-grow-1">
    
<BootstrapClient />
          {children}
       
 </div>
        <Footer />
        
      </body>
    </html>
  );
}
